### ISSUE TITLE
how to solve this?

### ISSUE THREAD

**Issue by aafnnp** [Aakash1103Jha/thedevdesigner-react-lib#7]
```bash
design-system  🍣 master via  v16.15.0 🐏 13GiB/16GiB | 256MiB/1024MiB 
🕙 15:38:25 ❯ pnpm build

> @ build /Users/pfan/workspaces/github/design-system
> turbo run build

• Packages in scope: , @manon/eslint-config, @manon/ui, @manon/utils, docs
• Running build in 5 packages
@manon/utils:build: cache hit, replaying output 765f139874e80ab2
@manon/utils:build: 
@manon/utils:build: > @manon/utils@0.0.0 build /Users/pfan/workspaces/github/design-system/packages/manon-utils
@manon/utils:build: > tsup src/index.ts --format esm,cjs --dts --external react
@manon/utils:build: 
@manon/utils:build: CLI Building entry: src/index.ts
@manon/utils:build: CLI Using tsconfig: tsconfig.json
@manon/utils:build: CLI tsup v5.12.9
@manon/utils:build: CLI Target: node12
@manon/utils:build: ESM Build start
@manon/utils:build: CJS Build start
@manon/utils:build: ESM ⚡️ Build success in 22ms
@manon/utils:build: CJS ⚡️ Build success in 9ms
@manon/utils:build: ESM dist/index.mjs 5.92 KB
@manon/utils:build: CJS dist/index.js 7.64 KB
@manon/utils:build: DTS Build start
@manon/utils:build: DTS ⚡️ Build success in 666ms
@manon/utils:build: DTS dist/index.d.ts 2.94 KB
@manon/ui:build: cache miss, executing 15ab2396fbe2d368
@manon/ui:build: 
@manon/ui:build: > @manon/ui@0.0.0 build /Users/pfan/workspaces/github/design-system/packages/manon-ui
@manon/ui:build: > npm run prebuild && rollup -c
@manon/ui:build: 
@manon/ui:build: 
@manon/ui:build: > @manon/ui@0.0.0 prebuild
@manon/ui:build: > rm -rf dist
@manon/ui:build: 
@manon/ui:build: 
@manon/ui:build: src/index.ts → dist/esm/index.js, dist/cjs/index.js...
@manon/ui:build: created dist/esm/index.js, dist/cjs/index.js in 1.1s
@manon/ui:build: 
@manon/ui:build: dist/esm/types/index.d.ts → dist/index.d.ts...
@manon/ui:build: [!] Error: Could not resolve entry module (dist/esm/types/index.d.ts).
@manon/ui:build: Error: Could not resolve entry module (dist/esm/types/index.d.ts).
@manon/ui:build:     at error (/Users/pfan/workspaces/github/design-system/node_modules/.pnpm/rollup@2.76.0/node_modules/rollup/dist/shared/rollup.js:198:30)
@manon/ui:build:     at ModuleLoader.loadEntryModule (/Users/pfan/workspaces/github/design-system/node_modules/.pnpm/rollup@2.76.0/node_modules/rollup/dist/shared/rollup.js:22527:20)
@manon/ui:build:     at async Promise.all (index 0)
@manon/ui:build: 
@manon/ui:build:  ELIFECYCLE  Command failed with exit code 1.
@manon/ui:build: ERROR: command finished with error: command (packages/manon-ui) pnpm run build exited (1)
command (packages/manon-ui) pnpm run build exited (1)

 Tasks:    1 successful, 2 total
Cached:    1 cached, 2 total
  Time:    2.096s 

 ELIFECYCLE  Command failed with exit code 1.
```

https://github.com/Manonicu/design-system

**Comment by Aakash1103Jha** [comment]
@Manonicu - you can refer to Issue #2 - same as this one.
You can either add a `.env` file at your project root and add `GENERATE_SOURCEMAP=false` in there. Then, restart your app with `npm start` and those warnings will be gone. 

This is an issue with CRA and webpack; already an open issue on cra's GitHub.
